### ISSUE TITLE
 Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out

### ISSUE THREAD

**Issue by scljy** [onplus/v2hero#12]
travis ci log
gpg:               imported: 1  (RSA: 1)
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
![qq 20171214135857](https://user-images.githubusercontent.com/26355632/33979620-22ef359a-e0e0-11e7-8f1c-1b66c132ccaf.png)

![screenshot_20171214-150521](https://user-images.githubusercontent.com/26355632/33979640-401be5be-e0e0-11e7-862c-a9704639320f.jpg)
![screenshot_20171214-150816](https://user-images.githubusercontent.com/26355632/33979754-c490b46e-e0e0-11e7-93e9-7f5fab7e1152.jpg)

**Comment by onplus** [comment]
![screenshot_2017-12-14-15-27-43](https://user-images.githubusercontent.com/31188782/33980364-8543bf88-e0e3-11e7-9ad7-92cccd828931.png)

**Comment by scljy** [comment]
![screenshot_20171214-160245](https://user-images.githubusercontent.com/26355632/33981580-69b1308e-e0e8-11e7-9829-a0dd5511f6b9.jpg)


017-12-14T07:57:40.375804+00:00 app[web.1]: An unified platform for anti-censorship.
2017-12-14T07:57:40.375787+00:00 app[web.1]: V2Ray v3.1 (die Commanderin) 20171207
2017-12-14T07:57:40.412985+00:00 app[web.1]: 2017/12/14 07:57:40 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:54622
2017-12-14T07:57:40.413281+00:00 app[web.1]: 2017/12/14 07:57:40 [Warning]Core: V2Ray started
2017-12-14T07:57:43.193765+00:00 heroku[router]: at=info method=GET path="/" host=v2ljy.herokuapp.com request_id=903ec2d7-28f4-46e6-9201-18bc1b171b25 fwd="111.112.252.211" dyno=web.1 connect=0ms service=313ms status=101 bytes=129 protocol=http
2017-12-14T07:57:45.152034+00:00 heroku[router]: at=info method=GET path="/" host=v2ljy.herokuapp.com request_id=42f379a5-4376-49a4-be60-366c5cb4f74a fwd="111.112.252.211" dyno=web.1 connect=1ms service=304ms status=101 bytes=129 protocol=http

![screenshot_20171214-150816](https://user-images.githubusercontent.com/26355632/33981662-b39b3e92-e0e8-11e7-9997-4dbffb482fe6.jpg)

**Comment by scljy** [comment]
测试服务器没有问题

**Comment by scljy** [comment]
@onplus   怎么检查服务器部署正常没有？

**Comment by onplus** [comment]
@scljy 最好用电脑测试(v2rayN)，手机客户端时有bug

**Comment by scljy** [comment]
![image](https://user-images.githubusercontent.com/26355632/34024333-7807081a-e184-11e7-9d31-32a2f4d40fd3.png)

**Comment by onplus** [comment]
下载最新的v2rayN1.2

**Comment by scljy** [comment]
好的

**Comment by scljy** [comment]
![qq 20171215110708](https://user-images.githubusercontent.com/26355632/34024993-4b163f3e-e188-11e7-9c01-e98e7192b979.png)

配置成功 
v2lxm(v2lxm.herokuapp.com:80)
启动服务(2017-12-15 11:04:15)......
V2Ray v3.1 (die Commanderin) 20171207
An unified platform for anti-censorship.
2017/12/15 11:04:15 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:1080
2017/12/15 11:04:15 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:1080
2017/12/15 11:04:15 [Info]Transport|Internet|UDP: listening UDP on 0.0.0.0:1080

配置正确 不？

**Comment by onplus** [comment]
只需要配置第一行

**Comment by scljy** [comment]
![w_5hfn7jfpzvn 3n1pvam2](https://user-images.githubusercontent.com/26355632/34025084-e20a9228-e188-11e7-9718-70a83ec17b24.png)

**Comment by scljy** [comment]
终于找到原因了，每次用户ID弄错了弄成了API key了。
