### ISSUE TITLE
Heroku是不是禁止用作fq用途了

### ISSUE THREAD

**Issue by jinke159** [onplus/v2hero#19]
禁止行为

除条款中描述的违规行为（和/或作为其中的一些例子）外，您不得也不得允许任何第三方（包括您的最终用户）： `20.Use the Service to operate an "open proxy" or any other form of Internet proxy service that is capable of forwarding requests to any End User or third party-supplied Internet host;
20.使用服务来运行“开放式代理”或任何其他形式的Internet代理服务，该服务能够将请求转发给任何最终用户或第三方提供的Internet主机;`
[Heroku](https://translate.google.com/translate?sl=en&tl=zh-CN&js=y&prev=_t&hl=zh-CN&ie=UTF-8&u=https%3A%2F%2Fwww.heroku.com%2Fpolicy%2Faup&edit-text=&act=url)

**Comment by onplus** [comment]
是的，很久之前就是禁止的

![image](https://user-images.githubusercontent.com/31188782/34298674-e8455d72-e759-11e7-9a49-05c5b0697c91.png)
