### ISSUE TITLE
travis build wrong

### ISSUE THREAD

**Issue by windleafy** [onplus/v2hero#3]
1. 0.39s$ docker login -u "$HEROKU_EMAIL" -p "$HEROKU_APIKEY" registry.heroku.com
2. Error response from daemon: login attempt to https://registry.heroku.com/v2/ failed with status: 401 Unauthorized
3. The command "docker login -u "$HEROKU_EMAIL" -p "$HEROKU_APIKEY" registry.heroku.com" failed and exited with 1 during .
4. Your build has been stopped.

**Comment by onplus** [comment]
apikey ，not password 
![image](https://user-images.githubusercontent.com/31188782/33434428-3f643ec6-d61a-11e7-800e-9e6ca05d9cf2.png)

**Comment by windleafy** [comment]
Thx

**Comment by windleafy** [comment]
new wrong
1. 0.41s$ docker login -u "$HEROKU_EMAIL" -p "$HEROKU_APIKEY" registry.heroku.com
2. Login Succeeded
3. 0.49s$ docker push registry.heroku.com/"$HEROKU_APPNAME"/web
4. The push refers to a repository [registry.heroku.com/hiv2hero.herokuapp.com/web]
5. error parsing HTTP 400 response body: unexpected end of JSON input: ""
