### ISSUE TITLE
环境变量配置完成后重新开始TraviCi Build没反应   

### ISSUE THREAD

**Issue by v2us2** [onplus/v2hero#4]
环境变量配置完成后重新开始TraviCi Build   
![snipaste_2017-12-01_09-23-25](https://user-images.githubusercontent.com/34145689/33463587-5be45b12-d679-11e7-831c-43d1b0f875ae.png)

**Comment by onplus** [comment]
修改一下自己项目的readme.md，看能不能触发build

**Comment by v2us2** [comment]
@onplus 谢谢。刚翻半天找到travis-c上的帮助文档，要对自己项目做任何改动即可触发。已解决。
但很奇怪用Firefox57+Proxy SwtichOmega打不开墙外网站，“安全连接失败”，好像是证书问题。用v2ray时出现，而用ss和ssr时一切正常。不知道是V2Ray还是Proxy SwtichOmega的问题。

**Comment by onplus** [comment]
用的端口是80还是443+tls ？IE或者chrome可以连接吗？

**Comment by v2us2** [comment]
其他一切都正常。只有Firefox+Proxy SwtichOmega时会这样。
应该是Proxy SwtichOmega的锅。

**Comment by v2us2** [comment]
@onplus 另外请问怎么在TravisCI里配置多个herokuapp？是不是要在github里复制多份v2hero？

**Comment by onplus** [comment]
执行步骤134567

**Comment by v2us2** [comment]
多谢。只是想在一个heroku账号里部署北美和欧洲两个。因为用起来感觉比我自建的好用，哈哈。
第三步里heroku邮箱和api key是一样的，所以只需要再添加一个HEROKU_APPNAME即可？

**Comment by onplus** [comment]
应该不会比VPS自建的好，，，

这个主要是给翻墙需求不是太大的用户选择的

整个流程就是
就是创建新的appname，到travisci环境变量修改appname，travisci build部署heroku

**Comment by chuhaibo** [comment]
@v2us2  请问“要对自己项目做任何改动即可触发”是怎么改的

**Comment by abchb99** [comment]
刚环境变量修改完，无内容，过一分钟左右，项目就显示出来了，要等下。
