### ISSUE TITLE
请问有没有 wangyi2005/v2ray-heroku 的部署步骤

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [onplus/v2hero#43]
点击部署，设置 appname，然后点创建，之后进入这个界面 ，不知道下一步该做什么
![default](https://user-images.githubusercontent.com/14090545/37082392-6eaf900a-2227-11e8-8a36-1f18565042b9.png)

**Comment by onplus** [comment]
部署完了，配置客户端就行

**Comment by LakeishaKowalczyk** [comment]
@onplus 
但是我打开 App，没有显示  Bad Request，可以吗
![default](https://user-images.githubusercontent.com/14090545/37083021-27384332-2229-11e8-8480-0b1074c36fdb.png)

**Comment by LakeishaKowalczyk** [comment]
配置客户端后无法使用，除了「地址」「用户ID」「别名」是自己设定生成的，别的和教程一样

![default](https://user-images.githubusercontent.com/14090545/37084668-1ca42a30-222e-11e8-8fdd-0649ba152b69.png)

**Comment by onplus** [comment]
https://dashboard.heroku.com/new?template=https://github.com/wangyi2005/v2ray-heroku

**Comment by onplus** [comment]
请在对应项目提issue

**Comment by LakeishaKowalczyk** [comment]
@onplus 
谢谢你，成功了

话说为什么居然竟然未必然出现的居然是这样的问题，绝倒中`````````````

**Comment by LakeishaKowalczyk** [comment]
@onplus 
谢谢你，成功了

话说为什么居然竟然未必然出现的居然是这样的问题，绝倒中`````````````
