### ISSUE TITLE
在ios上用Shadowrocket设置了没用啊

### ISSUE THREAD

**Issue by gggccc44** [onplus/v2hero#51]
安卓倒是轻松搞定，ios上Shadowrocket少了好多选项vmess无效，找了个ssr倒是能用，不过我要用的是这个自建的v2hero啊

**Comment by gggccc44** [comment]
可以關閉了，找到了高版本的，需要越獄，或者去其他區花錢買

**Comment by LightGal** [comment]
ios只找到一个 ShadowRocket - Wingy，看描述没有Vmess相关，不知道有谁知道支持么？

去其他区还要注册账号，充值还要礼品卡，略麻烦
