### ISSUE TITLE
默认的端口号是多少？

### ISSUE THREAD

**Issue by alexya** [onplus/v2hero#7]
看到你的配置里面只有uuid是需要自己生成填写的，但是那个PORT呢？
貌似用的默认值，那这个值是多少？

谢谢！

**Comment by onplus** [comment]
https://github.com/onplus/v2hero/blob/ci/entrypoint.sh

https://github.com/onplus/heroku_go-getting-started/blob/master/app.json

heroku的环境变量$PORT，无法指定，并且每次启动都不一样

**Comment by alexya** [comment]
你的意思是，
heroku每次启动，给这个app分配的端口是随机的，比如，这次是5555
然后，外面有连接到443的数据，都转发给5555么？
