### ISSUE TITLE
V2ray 4.6以上目录结构改变

### ISSUE THREAD

**Issue by trulymadly** [onplus/v2hero#74]
原来的脚本中，解压v2ray.zip后，要按照版本找目录，最近的release应该是已经把目录结构改了。我试着去掉了几句，build 成功
 && mkdir -m 777 /v2raybin \ 
 && cd /v2raybin \
 && curl -L -H "Cache-Control: no-cache" -o v2ray.zip https://github.com/v2ray/v2ray-core/releases/download/v$VER/v2ray-linux-64.zip \
 && unzip v2ray.zip \
 && chmod +x /v2raybin/v2ray \
 && rm -rf v2ray.zip \
 && chgrp -R 0 /v2raybin \
 && chmod -R g+rwX /v2raybin

**Comment by yllyx** [comment]
的确是这样的，现在部署成功了，但是使用v2rayNG无法连接服务器

**Comment by becapital** [comment]
按照教程失败啊，怎么弄呢。。。？

**Comment by wangmt2000** [comment]
heroku不能自己指定端口，开放的只有80，443端口，现在不知道怎么通过$port 映射到80。443

**Comment by willduan** [comment]
``` 
RUN apk add --no-cache --virtual .build-deps ca-certificates curl \
 && mkdir -m 777 /v2raybin \
 && cd /v2raybin \
 && curl -L -H "Cache-Control: no-cache" -o v2ray.zip https://github.com/v2ray/v2ray-core/releases/download/v$VER/v2ray-linux-64.zip \
 && unzip v2ray.zip \
 && chmod +x /v2raybin/v2ray \
 && rm -rf v2ray.zip \
 && chgrp -R 0 /v2raybin \
 && chmod -R g+rwX /v2raybin ```
是的，改成这样就好多了
